In [1]:
from utils import *
import numpy as np
from numpy import diag
import scipy
from scipy.linalg import lu, qr, cholesky, eig, inv
import scipy.linalg as linalg 

## LU Decomposition

In [2]:
A = create_matrix_random(4, 5, 1, 10)
A

array([[ 6,  5,  6,  6,  9],
       [ 6,  3,  6,  9,  3],
       [ 1,  9,  4, 10,  4],
       [ 5, 10,  4,  7, 10]])

In [3]:
P, L, U = lu(A)

In [4]:
P

array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [5]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.16666667,  1.        ,  0.        ,  0.        ],
       [ 0.83333333,  0.71428571,  1.        ,  0.        ],
       [ 1.        , -0.24489796, -0.23376623,  1.        ]])

In [6]:
U

array([[ 6.        ,  5.        ,  6.        ,  6.        ,  9.        ],
       [ 0.        ,  8.16666667,  3.        ,  9.        ,  2.5       ],
       [ 0.        ,  0.        , -3.14285714, -4.42857143,  0.71428571],
       [ 0.        ,  0.        ,  0.        ,  4.16883117, -5.22077922]])

In [7]:
B = P.dot(L).dot(U)
B

array([[ 6.,  5.,  6.,  6.,  9.],
       [ 6.,  3.,  6.,  9.,  3.],
       [ 1.,  9.,  4., 10.,  4.],
       [ 5., 10.,  4.,  7., 10.]])

In [8]:
# define matrix A using Numpy arrays 
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]]) 

# define matrix B 
B = np.array([4, 5, 6]) 

# With LU = A
LU = linalg.lu_factor(A) 

#solve given LU and B 
x = linalg.lu_solve(LU, B) 
print("Solutions(a, b, c):\n",x) 

Solutions(a, b, c):
 [  6.  15. -23.]


In [11]:
P, L, U = scipy.linalg.lu(A) 

In [12]:
# define matrix A using Numpy arrays 
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]]) 

In [13]:
LU = linalg.lu_factor()

In [20]:
P, L, U = lu(A)

In [21]:
P

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
L

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  1. ,  0. ],
       [ 0.5, -0.2,  1. ]])

In [23]:
U

array([[ 2. ,  1. ,  1. ],
       [ 0. ,  2.5,  1.5],
       [ 0. ,  0. , -0.2]])

In [26]:
LU[0]

array([[ 2. ,  1. ,  1. ],
       [ 0.5,  2.5,  1.5],
       [ 0.5, -0.2, -0.2]])

In [27]:
LU[1]

array([0, 1, 2], dtype=int32)

In [28]:
B.shape

(3,)

## QR Decomposition

In [9]:
B = create_matrix_random(4, 4, 5, 10)
B

array([[ 5,  7,  8, 10],
       [ 8,  6,  5,  8],
       [ 9,  7,  9,  9],
       [10,  7, 10,  7]])

In [10]:
Q, R = qr(B)

In [11]:
Q

array([[-0.30429031,  0.93933644, -0.06085806,  0.146119  ],
       [-0.4868645 , -0.12524486,  0.85201287,  0.146119  ],
       [-0.54772256, -0.06262243, -0.18257419, -0.81409158],
       [-0.60858062, -0.31311215, -0.4868645 ,  0.54272772]])

In [12]:
R

array([[-16.43167673, -13.14534138, -15.88395417, -16.12738642],
       [  0.        ,   3.19374388,   3.19374388,   5.63601862],
       [  0.        ,   0.        ,  -2.73861279,   1.15630318],
       [  0.        ,   0.        ,   0.        ,  -0.89758815]])

In [13]:
C = Q.dot(R)
C

array([[ 5.,  7.,  8., 10.],
       [ 8.,  6.,  5.,  8.],
       [ 9.,  7.,  9.,  9.],
       [10.,  7., 10.,  7.]])

## Cholesky 

In [14]:
def create_matrix_positive_definite(m, n, start, end):
    E = None
    flag = False
    while flag == False:
        E =  create_matrix_random(m, n, start, end)
        for i in range(E.shape[0]):
            for j in range(i):
                E[j][i] = E[i][j]
        test = np.linalg.eigvalsh(E)
        flag = np.all(test>0)
    return E

In [15]:
E = create_matrix_positive_definite(3, 3, 3, 9)
E

array([[9, 8, 6],
       [8, 9, 7],
       [6, 7, 8]])

In [16]:
L = cholesky(E)
print(L)

[[3.         2.66666667 2.        ]
 [0.         1.37436854 1.21267813]
 [0.         0.         1.59041245]]


In [17]:
F = L.dot(L.T)
print(F)

[[20.11111111  6.09033903  3.1808249 ]
 [ 6.09033903  3.35947712  1.92865839]
 [ 3.1808249   1.92865839  2.52941176]]


## Eigen Decomposition

In [18]:
A = create_matrix_random(5, 5, 1, 10)
A

array([[ 6, 11,  7,  6,  3],
       [10,  5,  8, 10, 10],
       [ 4,  2, 10,  6,  7],
       [ 2,  5,  6,  5,  8],
       [ 1,  1,  9,  8,  2]])

In [19]:
values, vectors = eig(A)

In [20]:
# Confirm first eigenvector
B = A.dot(vectors[:,0])
B

array([-15.51150048+0.j, -17.71796747+0.j, -11.23641779+0.j,
       -10.37336665+0.j,  -7.99242718+0.j])

In [21]:
C = vectors[:, 0] * values[0]
C

array([-15.51150048+0.j, -17.71796747+0.j, -11.23641779+0.j,
       -10.37336665+0.j,  -7.99242718+0.j])

In [24]:
Q = vectors
R = inv(Q)
L = diag(values)

In [25]:
A_new = Q.dot(L).dot(R)
A_new

array([[ 6.-1.10190820e-15j, 11.+4.85958337e-16j,  7.+6.40114310e-16j,
         6.+8.98292410e-16j,  3.-1.24410322e-15j],
       [10.-8.47264311e-16j,  5.+6.86071862e-16j,  8.+2.09611494e-16j,
        10.+9.62717359e-16j, 10.-1.18711272e-15j],
       [ 4.-4.85558004e-16j,  2.+3.59659954e-16j, 10.+1.47608927e-16j,
         6.+4.36299491e-16j,  7.-4.79117389e-16j],
       [ 2.-5.13640356e-16j,  5.+1.79875766e-16j,  6.+2.94837262e-16j,
         5.+4.27404319e-16j,  8.-4.81020361e-16j],
       [ 1.-6.03621368e-16j,  1.+3.74744090e-16j,  9.+1.98616181e-16j,
         8.+2.24982608e-16j,  2.-4.58798418e-16j]])